#!/usr/bin/env bash
# -----------------------------------------------------------------------------
# 4-qchem-solvent-opt.sh – Optimise every conformer in implicit solvent (SMD)
#                          with Q-Chem and submit each job via SLURM.
#
# INPUT  : <tag>/qchem_opt_conf/split_xyz/<tag>_N.xyz     (from script 3)
# OUTPUT : <tag>/solvent_opt/<CID>/{CID}.out/.inp/.slurm
#
# CLI *superset* (matches every step in the workflow)
#   -m/--method, -b/--basis, --disp, --grid, --cpus, --mem-per-cpu
# plus step-specific flags: --solvent, --max-scf-cycles, --list, --dry-run
# -----------------------------------------------------------------------------
set -euo pipefail
IFS=$'\n\t'

# ----------------------------- defaults --------------------------------------
DEFAULT_SOLVENT="water"
DEFAULT_METHOD="B3LYP"           # no dispersion suffix
DEFAULT_BASIS="6-31+G(d)"
DEFAULT_DISP="none"              # {none,auto,D3BJ}
DEFAULT_CPUS=12
DEFAULT_MEM_MB=2048
DEFAULT_PART="circe"
DEFAULT_MAX_SCF=150
DEFAULT_WALL="02:00:00"
XYZ_DIR="pre_xyz"

# ----------------------------- helpers ---------------------------------------
die()  { printf 'Error: %s\n' "$*" >&2; exit 1; }
note() { printf '\n[%s] %s\n' "$(date +%H:%M:%S)" "$*" >&2; }
pre_xyz() { printf '%s/%s.xyz' "$XYZ_DIR" "$1"; }
charge_mult() { awk 'NR==2{print $1,$2}' "$1"; }
cid_of() { basename "$1" .xyz; }

show_help() {
cat <<EOF
Usage:
  $(basename "$0") [OPTIONS] tag_or_xyz
  $(basename "$0") --list file.txt [OPTIONS]

Common flags (parsed but ignored where irrelevant):
  -m/--method METH       Electronic method           [$DEFAULT_METHOD]
  -b/--basis  BASIS      Basis set                   [$DEFAULT_BASIS]
  --disp {none,auto,D3BJ}  Dispersion handling       [$DEFAULT_DISP]
  --grid SGn             (ignored here, for parity)
  --cpus N               CPUs per job                [$DEFAULT_CPUS]
  --mem-per-cpu MB       Memory per CPU (MB)         [$DEFAULT_MEM_MB]

Step-specific:
  --solvent NAME         SMD solvent                 [$DEFAULT_SOLVENT]
  --max-scf-cycles N     MAX_SCF_CYCLES              [$DEFAULT_MAX_SCF]
  --partition NAME       SLURM partition             [$DEFAULT_PART]
  --list FILE            Tags or XYZ paths
  --dry-run              Create files, do not submit
  -h, --help             Show this help
EOF
}

# --------------------------- CLI parsing -------------------------------------
parse_cli() {
  SOLVENT=$DEFAULT_SOLVENT
  METHOD=$DEFAULT_METHOD
  BASIS=$DEFAULT_BASIS
  DISP_MODE=$DEFAULT_DISP
  CPUS=$DEFAULT_CPUS
  MEM_MB=$DEFAULT_MEM_MB
  PART=$DEFAULT_PART
  MAX_SCF=$DEFAULT_MAX_SCF
  DRY=false
  LIST=""
  SINGLE=""

  local opts
  opts=$(getopt -o hb:m: --long help,basis:,method:,disp:,grid:,solvent:,cpus:,mem-per-cpu:,partition:,max-scf-cycles:,list:,dry-run -- "$@")
  eval set -- "$opts"
  while true; do
    case "$1" in
      --solvent)          SOLVENT=$2; shift 2;;
      -m|--method)        METHOD=$2; shift 2;;
      -b|--basis)         BASIS=$2; shift 2;;
      --disp)             DISP_MODE=$2; shift 2;;
      --grid)             shift 2;;                     # ignored
      --cpus)             CPUS=$2; shift 2;;
      --mem-per-cpu)      MEM_MB=$2; shift 2;;
      --partition)        PART=$2; shift 2;;
      --max-scf-cycles)   MAX_SCF=$2; shift 2;;
      --list)             LIST=$2; shift 2;;
      --dry-run)          DRY=true; shift;;
      -h|--help)          show_help; exit 0;;
      --) shift; break;;
      *) die "Unknown option $1";;
    esac
  done

  # If --list is not used we need exactly one positional token
  if [[ -n $LIST ]]; then
    [[ $# -eq 0 ]] || die "No positional args allowed with --list"
    [[ -f $LIST ]] || die "List file '$LIST' not found"
  else
    [[ $# -eq 1 ]] || die "Provide a tag or XYZ path"
    SINGLE=$1
  fi

  command -v sbatch >/dev/null 2>&1 || die "sbatch not in PATH"
}

# ------------------------- dispersion handling -------------------------------
make_dft_d_line() {
  local meth_uc=${METHOD^^}
  case $DISP_MODE in
    none) echo ""; return ;;
    D3BJ) echo "  DFT_D              D3_BJ"; return ;;
    auto)
      [[ $meth_uc =~ (-D|D3|D4|-V)$ ]] && { echo ""; return; }
      echo "  DFT_D              D3_BJ"; return ;;
    *) die "--disp must be none, auto, or D3BJ" ;;
  esac
}

# ---------------------- writers ------------------------------------------------
write_input() {
  local TAG=$1 CID=$2 XYZ=$3 OUT=$4
  local CH=0 ML=1
  local PX; PX=$(pre_xyz "$TAG")
  [[ -f $PX ]] && read -r CH ML < <(charge_mult "$PX")

  local DFT_D_LINE; DFT_D_LINE=$(make_dft_d_line)

  cat >"$OUT" <<EOF
\$comment
Implicit-solvent optimisation of $CID (generated by 4-qchem-solvent-opt.sh)
\$end

\$molecule
$CH $ML
$(tail -n +3 "$XYZ")
\$end

\$rem
  JOB_TYPE            OPT
  METHOD              $METHOD
  BASIS               $BASIS
  SOLVENT_METHOD      SMD
  MAX_SCF_CYCLES      $MAX_SCF
  SCF_CONVERGENCE     8
  SYM_IGNORE          TRUE
  THRESH              11
  XC_GRID             3
$DFT_D_LINE
\$end

\$smx
  solvent             $SOLVENT
\$end
EOF
}

write_slurm() {
  local CID=$1 INP=$2 OUT=$3 SLM=$4
  cat >"$SLM" <<EOF
#!/usr/bin/env bash
#SBATCH --job-name=${CID}
#SBATCH --partition=${PART}
#SBATCH --nodes=1
#SBATCH --cpus-per-task=${CPUS}
#SBATCH --mem-per-cpu=${MEM_MB}
#SBATCH --time=${DEFAULT_WALL}
#SBATCH --output=slurm-%j.out
#SBATCH --error=slurm-%j.err

module purge
source /shares/chem_hlw/qchem/7.0.0-qmmm-nt-intel-pre/setqc
export QCSCRATCH=/tmp/\$SLURM_JOBID

qchem -nt ${CPUS} $(basename "$INP") $(basename "$OUT")
EOF
  chmod +x "$SLM"
}

# ---------------------- job submission helpers -------------------------------
submit_conf() {
  local TAG=$1 XYZ=$2
  local CID; CID=$(cid_of "$XYZ")
  local DIR="${TAG}/solvent_opt/${CID}"
  mkdir -p "$DIR"

  local INP="$DIR/${CID}.inp"
  local OUT="$DIR/${CID}.out"
  local SLM="$DIR/${CID}.slurm"

  write_input "$TAG" "$CID" "$XYZ" "$INP"
  write_slurm "$CID" "$INP" "$OUT" "$SLM"

  if $DRY; then
    note "[$TAG] sbatch --chdir=$DIR $(basename "$SLM")"
  else
    sbatch --chdir="$DIR" "$(basename "$SLM")"
  fi
}

process_tag() {
  local TAG=$1
  local SPLIT_XYZ_DIR="${TAG}/qchem_opt_conf/split_xyz"
  [[ -d $SPLIT_XYZ_DIR ]] || { note "[$TAG] split_xyz dir missing"; return; }
  shopt -s nullglob
  local XYZS=("${SPLIT_XYZ_DIR}/${TAG}_"*.xyz)
  shopt -u nullglob
  [[ ${#XYZS[@]} -eq 0 ]] && { note "[$TAG] no conformers"; return; }
  note "[$TAG] Found ${#XYZS[@]} conformers"
  for X in "${XYZS[@]}"; do submit_conf "$TAG" "$X"; done
}

handle_entry() {
  if [[ $1 == *.xyz ]]; then
    local TAG; TAG=$(cid_of "$1" | sed 's/_.*//')
    process_tag "$TAG"
  else
    process_tag "$1"
  fi
}

# -------------------------------- main ---------------------------------------
main() {
  parse_cli "$@"

  if [[ -n $LIST ]]; then
    while IFS= read -r line || [[ -n $line ]]; do
      [[ $line =~ ^[[:space:]]*$ ]] && continue
      [[ $line =~ '^[[:space:]]*[#;]' ]] && continue
      handle_entry "$line"
    done <"$LIST"
  else
    handle_entry "$SINGLE"
  fi

  $DRY && note "Dry run complete – no jobs submitted"
}

main "$@"
