#!/usr/bin/env bash
# -----------------------------------------------------------------------------
# 6-qchem-tddft.sh – Submit TD-DFT (UV-Vis + ECD) single-point calculations in
#                    implicit solvent for every Boltzmann-kept conformer.
# -----------------------------------------------------------------------------
# Uses SMD by default (water); choose another solvent via --solvent.
# Geometry is extracted on-the-fly from the solvent_opt output files (step 4).
# -----------------------------------------------------------------------------
set -euo pipefail
IFS=$'\n\t'

# --------------------------- default parameters ---------------------------
DEFAULT_METHOD="B3LYP"
DEFAULT_BASIS="6-31+G(d)"
DEFAULT_ROOTS=30
DEFAULT_SOLVENT="water"
DEFAULT_CPUS=12
DEFAULT_MEM=2048           # MB per CPU
DEFAULT_PART=circe
DEFAULT_WALL="4:00:00"
DEFAULT_MAX_SCF=150
SOLV_OUT_DIR="solvent_opt"   # <tag>/solvent_opt/<CID>/<CID>.out
PRE_DIR="pre_xyz"            # charge/mult source

# ------------------------------ utilities ---------------------------------
log(){ printf '\n[%s] %s\n' "$(date +%H:%M:%S)" "$*" >&2; }
err(){ echo "Error: $*" >&2; exit 1; }
pre_xyz(){ printf '%s/%s.xyz' "$PRE_DIR" "$1"; }
charge_mult(){ awk 'NR==2{print $1,$2}' "$1"; }

# ---- on-the-fly geometry extractor (last optimised geometry from .out) ------
qcout2xyz(){ python3 - "$1" <<'PY'
import pathlib, re, sys
lines=pathlib.Path(sys.argv[1]).read_text(errors="ignore").splitlines()
hdr=re.compile(r'(Standard Nuclear Orientation|Input orientation|Coordinates \(Angstroms\))',re.I)
start=None
for i in range(len(lines)-1,-1,-1):
    if hdr.search(lines[i]): start=i+3; break
if start is None: sys.exit(1)
geom=[]
for l in lines[start:]:
    if not l.strip() or l.lstrip().startswith('-'): break
    p=l.split()
    if len(p)>=5: sym,x,y,z=p[1:5]
    elif len(p)==4: sym,x,y,z=p
    else: continue
    geom.append(f"{sym} {x} {y} {z}")
print(len(geom));print();print("\n".join(geom))
PY
}

# ------------------------------ CLI parser -------------------------------
parse_cli(){
  METHOD=$DEFAULT_METHOD; BASIS=$DEFAULT_BASIS; ROOTS=$DEFAULT_ROOTS
  SOLVENT=$DEFAULT_SOLVENT
  CPUS=$DEFAULT_CPUS; MEM=$DEFAULT_MEM; PART=$DEFAULT_PART
  DRY=false; LIST=""; SINGLE=""

  local opts
  opts=$(getopt -o h --long help,method:,basis:,roots:,solvent:,cpus:,mem-per-cpu:,partition:,list:,dry-run -- "$@")
  eval set -- "$opts"
  while true; do
    case "$1" in
      --method) METHOD=$2; shift 2;;
      --basis)  BASIS=$2; shift 2;;
      --roots)  ROOTS=$2; shift 2;;
      --solvent) SOLVENT=$2; shift 2;;
      --cpus)   CPUS=$2; shift 2;;
      --mem-per-cpu) MEM=$2; shift 2;;
      --partition) PART=$2; shift 2;;
      --list) LIST=$2; shift 2;;
      --dry-run) DRY=true; shift;;
      -h|--help)
        cat <<EOF
Usage:
  $(basename "$0") MoleculeTag [OPTIONS]
  $(basename "$0") --list tags.txt [OPTIONS]

Options:
  --method FUNC        TD-DFT functional            [${DEFAULT_METHOD}]
  --basis BASIS        Basis set                    [${DEFAULT_BASIS}]
  --roots N            Number of excited states     [${DEFAULT_ROOTS}]
  --solvent NAME       Implicit solvent (SMD)       [${DEFAULT_SOLVENT}]
  --cpus N             CPUs per job                 [${DEFAULT_CPUS}]
  --mem-per-cpu MB     Memory per CPU (MB)          [${DEFAULT_MEM}]
  --partition NAME     SLURM partition              [${DEFAULT_PART}]
  --list FILE          File with molecule tags      (blank/# ignored)
  --dry-run            Echo actions only
  -h, --help           Show this help and exit
EOF
        exit 0;;
      --) shift; break;;
      *) err "Unknown option $1";;
    esac
  done

  if [[ -n $LIST ]]; then
    [[ $# -eq 0 ]] || err "Unexpected positional argument with --list"
    [[ -f $LIST ]] || err "List file '$LIST' not found"
  else
    [[ $# -eq 1 ]] || err "Provide molecule tag when not using --list"
    SINGLE=$1
  fi

  command -v sbatch >/dev/null 2>&1 || err 'sbatch command not found in PATH'
}

# --------------------------- input & slurm writers ------------------------
write_input(){
  local TAG=$1 CID=$2 XYZ=$3 OUT=$4
  local CHARGE=0 MULT=1
  local PXYZ; PXYZ=$(pre_xyz "$TAG")
  [[ -f $PXYZ ]] && read -r CHARGE MULT < <(charge_mult "$PXYZ")

  cat >"$OUT" <<EOF
\$comment
TD-DFT UV-Vis + ECD (SMD ${SOLVENT}) generated by 6-qchem-tddft.sh
\$end

\$molecule
${CHARGE} ${MULT}
$(tail -n +3 "$XYZ")
\$end

\$rem
  JOB_TYPE            SP
  METHOD              ${METHOD}
  BASIS               ${BASIS}
  CIS_N_ROOTS         ${ROOTS}
  CIS_SINGLETS        TRUE
  CIS_TRIPLETS        FALSE
  RPA                 TRUE
  STS_MOM             TRUE
  CIS_MOMENTS         TRUE
  SOLVENT_METHOD      SMD
  SCF_CONVERGENCE     8
  MAX_SCF_CYCLES      ${DEFAULT_MAX_SCF}
  SYM_IGNORE          TRUE
  XC_GRID             3
\$end
EOF
  if [[ ${SOLVENT,,} != water ]]; then
    cat >>"$OUT" <<EOF

\$smx
solvent ${SOLVENT}
StateSpecific
\$end
EOF
  fi
}

write_slurm(){
  local JOB=$1 INP=$2 OUT=$3 SLM=$4
  cat >"$SLM" <<EOF
#!/usr/bin/env bash
#SBATCH --job-name=${JOB}
#SBATCH --partition=${PART}
#SBATCH --nodes=1
#SBATCH --cpus-per-task=${CPUS}
#SBATCH --mem-per-cpu=${MEM}
#SBATCH --time=${DEFAULT_WALL}
#SBATCH --output=slurm-%j.out
#SBATCH --error=slurm-%j.err

module purge
source /shares/chem_hlw/qchem/7.0.0-qmmm-nt-intel-pre/setqc
export QCSCRATCH=/tmp/\$SLURM_JOBID

qchem -nt ${CPUS} $(basename "$INP") $(basename "$OUT")
EOF
  chmod +x "$SLM"
}

# --------------------------- submission pipeline --------------------------
submit_one(){
  local TAG=$1 CID=$2 OUTFILE=$3
  local DIR="${TAG}/tddft/${CID}"; mkdir -p "$DIR"

  local XYZ_TMP; XYZ_TMP=$(mktemp --suffix=.xyz)
  qcout2xyz "$OUTFILE" > "$XYZ_TMP" || { log "[$TAG] cannot parse $CID"; rm -f "$XYZ_TMP"; return; }

  local INP="$DIR/$CID.inp" OUT="$DIR/$CID.out" SLM="$DIR/$CID.slurm"
  write_input "$TAG" "$CID" "$XYZ_TMP" "$INP"
  write_slurm "$CID" "$INP" "$OUT" "$SLM"
  rm -f "$XYZ_TMP"

  if $DRY; then
    log "[$TAG] sbatch --chdir=$DIR $(basename "$SLM")"
  else
    sbatch --chdir="$DIR" "$(basename "$SLM")"
  fi
}

process_tag(){
  local TAG=$1
  local LAB="${TAG}/bw_results/${TAG}_bw_labels.dat"
  [[ -f $LAB ]] || { log "[$TAG] label list not found"; return; }
  mapfile -t CIDS < <(grep -v '^[[:space:]]*$' "$LAB")
  [[ ${#CIDS[@]} -eq 0 ]] && { log "[$TAG] label list empty"; return; }

  for CID in "${CIDS[@]}"; do
    local OUTPATH="$TAG/$SOLV_OUT_DIR/$CID/$CID.out"
    [[ -f $OUTPATH ]] || { log "[$TAG] missing $CID.out"; continue; }
    submit_one "$TAG" "$CID" "$OUTPATH"
  done
}

handle(){ [[ $1 == *.xyz ]] && process_tag "$(basename "$1" .xyz)" || process_tag "$1"; }

# ------------------------------- main -------------------------------------
main(){
  parse_cli "$@"
  if [[ -n $LIST ]]; then
    while IFS= read -r TAG || [[ -n $TAG ]]; do
      [[ -z $TAG || $TAG == \#* ]] && continue
      handle "$TAG"
    done < "$LIST"
  else
    handle "$SINGLE"
  fi
}

main "$@"
