#!/usr/bin/env bash
# 6-qchem-vcd.sh – IR+VCD frequencies for Boltzmann-kept conformers (SMD).
# -----------------------------------------------------------------------------
set -euo pipefail
IFS=$'\n\t'

# ---------------- defaults ---------------------------------------------------
DEFAULT_METHOD="B3LYP"
DEFAULT_BASIS="6-31+G(d)"
DEFAULT_SOLVENT="water"
DEFAULT_CPUS=12
DEFAULT_MEM_MB=2048
DEFAULT_PART=circe
DEFAULT_WALL="06:00:00"
DEFAULT_MAX_SCF=150

SOLV_OUT_DIR="solvent_opt"        # geometry source = optimised .out files
PRE_DIR="pre_xyz"

# ---------------- helper funcs ----------------------------------------------
die(){ printf 'Error: %s\n' "$*" >&2; exit 1; }
note(){ printf '\n[%s] %s\n' "$(date +%H:%M:%S)" "$*" >&2; }
pre_xyz(){ printf '%s/%s.xyz' "$PRE_DIR" "$1"; }
charge_mult(){ awk 'NR==2{print $1,$2}' "$1"; }

# ------------- on-the-fly extractor (same as script 2 & 6-ecd) --------------
qcout2xyz(){ python3 - "$1" <<'PY'
import pathlib, re, sys
txt=pathlib.Path(sys.argv[1]).read_text(errors="ignore").splitlines()
hdr=re.compile(r'(Standard Nuclear Orientation|Input orientation|Coordinates \(Angstroms\))',re.I)
start=None
for i in range(len(txt)-1,-1,-1):
    if hdr.search(txt[i]): start=i+3; break
if start is None: sys.exit(1)
geom=[]
for l in txt[start:]:
    if not l.strip() or l.lstrip().startswith('-'): break
    p=l.split()
    if len(p)>=5: sym,x,y,z=p[1:5]
    elif len(p)==4: sym,x,y,z=p
    else: continue
    geom.append(f"{sym} {x} {y} {z}")
print(len(geom));print();print("\n".join(geom))
PY
}

# ---------------- CLI parsing ------------------------------------------------
parse_cli(){
  METHOD=$DEFAULT_METHOD; BASIS=$DEFAULT_BASIS; SOLVENT=$DEFAULT_SOLVENT
  CPUS=$DEFAULT_CPUS; MEM_MB=$DEFAULT_MEM_MB; PART=$DEFAULT_PART
  LIST=""; SINGLE=""; DRY=false

  local opts
  opts=$(getopt -o h --long help,method:,basis:,solvent:,cpus:,mem-per-cpu:,partition:,list:,dry-run -- "$@")
  eval set -- "$opts"
  while true; do
    case "$1" in
      --method) METHOD=$2; shift 2;;
      --basis)  BASIS=$2; shift 2;;
      --solvent)SOLVENT=$2; shift 2;;
      --cpus)   CPUS=$2; shift 2;;
      --mem-per-cpu) MEM_MB=$2; shift 2;;
      --partition) PART=$2; shift 2;;
      --list)   LIST=$2; shift 2;;
      --dry-run) DRY=true; shift;;
      -h|--help)
        sed -n '2,60p' "$0"; exit 0;;
      --) shift; break;;
      *) die "Unknown option $1";;
    esac
  done
  if [[ -n $LIST ]]; then
    [[ $# -eq 0 ]] || die "Positional args not allowed with --list"
    [[ -f $LIST ]] || die "List file '$LIST' not found"
  else
    [[ $# -eq 1 ]] || die "Provide a molecule tag"
    SINGLE=$1
  fi
  command -v sbatch >/dev/null 2>&1 || die "sbatch not in PATH"
}

# ---------------- writers ----------------------------------------------------
write_input(){
  local TAG=$1 CID=$2 XYZ=$3 OUT=$4
  local CH=0 ML=1
  local P=$(pre_xyz "$TAG"); [[ -f $P ]] && read -r CH ML < <(charge_mult "$P")
  local MEM_TOTAL=$((CPUS * MEM_MB))

cat >"$OUT" <<EOF
\$comment
IR + VCD (SMD $SOLVENT) – generated by 6-qchem-vcd.sh
\$end

\$molecule
$CH $ML
$(tail -n +3 "$XYZ")
\$end

\$rem
  JOB_TYPE            FREQ
  METHOD              $METHOD
  BASIS               $BASIS
  VCD                 TRUE
  RAMAN               TRUE
  SOLVENT_METHOD      SMD
  MAX_SCF_CYCLES      $DEFAULT_MAX_SCF
  SCF_CONVERGENCE     8
  SYM_IGNORE          TRUE
  XC_GRID             3
  MEM_TOTAL           $MEM_TOTAL
  MEM_STATIC          500
\$end
EOF

  if [[ ${SOLVENT,,} != water ]]; then
cat >>"$OUT" <<EOF

\$smx
  solvent $SOLVENT
\$end
EOF
  fi
}

write_slurm(){
  local CID=$1 INP=$2 OUT=$3 SLM=$4
cat >"$SLM" <<EOF
#!/usr/bin/env bash
#SBATCH --job-name=$CID
#SBATCH --partition=$PART
#SBATCH --nodes=1
#SBATCH --cpus-per-task=$CPUS
#SBATCH --mem-per-cpu=$MEM_MB
#SBATCH --time=$DEFAULT_WALL
#SBATCH --output=slurm-%j.out
#SBATCH --error=slurm-%j.err

module purge
source /shares/chem_hlw/qchem/7.0.0-qmmm-nt-intel-pre/setqc
export QCSCRATCH=/tmp/\$SLURM_JOBID

qchem -nt $CPUS \$(basename "$INP") \$(basename "$OUT")
EOF
  chmod +x "$SLM"
}

# ---------------- main workhorses -------------------------------------------
submit_one(){
  local TAG=$1 CID=$2 OUTPATH=$3
  local DIR="$TAG/vcd/$CID"; mkdir -p "$DIR"

  local XYZ_TMP; XYZ_TMP=$(mktemp --suffix=.xyz)
  qcout2xyz "$OUTPATH" > "$XYZ_TMP" || { note "[$TAG] cannot parse $CID"; rm -f "$XYZ_TMP"; return; }

  local INP="$DIR/$CID.inp" OUT="$DIR/$CID.out" SLM="$DIR/$CID.slurm"
  write_input "$TAG" "$CID" "$XYZ_TMP" "$INP"
  write_slurm "$CID" "$INP" "$OUT" "$SLM"
  rm -f "$XYZ_TMP"

  if $DRY; then
    note "[$TAG] sbatch --chdir=$DIR $(basename "$SLM")"
  else
    sbatch --chdir="$DIR" "$(basename "$SLM")"
  fi
}

process_tag(){
  local TAG=$1
  local LAB="$TAG/bw_results/${TAG}_bw_labels.dat"
  [[ -f $LAB ]] || { note "[$TAG] label list missing"; return; }
  mapfile -t CIDS < <(grep -v '^[[:space:]]*$' "$LAB")
  [[ ${#CIDS[@]} -eq 0 ]] && { note "[$TAG] label list empty"; return; }

  for CID in "${CIDS[@]}"; do
    local OUTFILE="$TAG/$SOLV_OUT_DIR/$CID/$CID.out"
    [[ -f $OUTFILE ]] || { note "[$TAG] missing $CID.out"; continue; }
    submit_one "$TAG" "$CID" "$OUTFILE"
  done
}

# -------------------------------- main ---------------------------------------
main(){
  parse_cli "$@"
  if [[ -n $LIST ]]; then
    grep -vE '^[[:space:]]*(#|;|$)' "$LIST" | while read -r tag; do
      process_tag "$tag"
    done
  else
    process_tag "$SINGLE"
  fi
  $DRY && note "Dry run complete - no jobs submitted"
}

main "$@"
